---
{{ include "cozy-lib.etcd.datastore" (dict "name" "etcd" "dataStoreName" .Release.Namespace "root" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-ca-tls
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-tls
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
