{{- if .Values.addons.hami.enabled }}
{{- if not .Values.addons.gpuOperator.enabled }}
{{- fail "addons.hami requires addons.gpuOperator to be enabled" }}
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-hami
  labels:
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: {{ .Release.Name }}
    sharding.fluxcd.io/key: tenants
spec:
  releaseName: hami
  chartRef:
    kind: ExternalArtifact
    name: cozystack-kubernetes-application-kubevirt-kubernetes-hami
    namespace: cozy-system
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: cozy-hami
  storageNamespace: cozy-hami
  interval: 5m
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- with .Values.addons.hami.valuesOverride }}
  values:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  dependsOn:
  - name: {{ .Release.Name }}-cilium
    namespace: {{ .Release.Namespace }}
  - name: {{ .Release.Name }}-gpu-operator
    namespace: {{ .Release.Namespace }}
{{- end }}
